### ISSUE TITLE
Error Message of minimize_x(H,v) unclear

### ISSUE THREAD

**Issue by retowildhaber** [lmlib/lmlib#12]
If "h" (or "H") Parameter in function .minimize_x(H,v) is of illegal dimension, the following error message appears:

Traceback (most recent call last):
  File "lcr-amplitude-fixed.py", line 64, in <module>
    xs_A = se_param.minimize_x(H_A, h_A)
  File "/Users/wbr8/Library/Python/3.8/lib/python/site-packages/lmlib/statespace/cost.py", line 1263, in minimize_x
    v, H, h = self.minimize_v(H, h, return_constrains=True)
  File "/Users/wbr8/Library/Python/3.8/lib/python/site-packages/lmlib/statespace/cost.py", line 1208, in minimize_v
    assert h.shape == (N,), ""
AssertionError

Improvement: The error message should return the observed and the expected dimension of h and H, resp.

**Comment by fwaldmann** [comment]
created branch and added assertion messages
